baseURL = "https://www.mojia.org/"
languageCode = "zh-CN"
title = "墨家Mojia"
theme = "hugo-diary-main"

[params]
subtitle = "一个人的独白"
description = "一个人的独白"
enableGiscus = true
disableDarkmode = false

[markup]
  [markup.highlight]
    noClasses = false

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  url = "/categories"
  name = "Categories"
  weight = 2

[[menu.main]]
  url = "/tags"
  name = "Tags"
  weight = 3

[[menu.main]]
  url = "/posts"
  name = "Archive"
  weight = 1
